### ISSUE TITLE
Add output dir and filename options

### ISSUE THREAD

**Issue by tafelito** [Scout24-CH/styled-svg#1]
It would be great if you could add the output directory of the generated files and specify a file name in . case of individuals files or a prefix for multi or the use of proper case and maybe remove the original svg file?

Another thing would be also to add some props to it, so if you want to set a different size or color  you can do it. Right now you have to set the noStyles in order to set the width & height but there is no way of changing the color

Thanks

**Comment by jaggli** [comment]
Thank you for your suggestions, let me split it up a little

**Overriding styles**
You can do this already, with the .extend method from styled-components. I updated the [docs](https://github.com/Scout24-CH/styled-svg/blob/master/README.md#overriding-styles). This is also how you can change the fill colors.

As the components are just regular styled-components, overriding styles is easy
```js
import React from 'react'
import ArrowDown from './ArrowDown'

const CustomizedArrowDown = ArrowDown.extend`
  width: 100%;
  border-radius: 3px;
  > path {
    fill: red;
  }
`
```

We will look into the following things
- Option for removing the original svg file
- Custom output directory
- Custom filename structure
