### ISSUE TITLE
Is there a way of disabling test generation?

### ISSUE THREAD

**Issue by apn2qq** [Scout24-CH/styled-svg#10]
Hi there, you have an excellent library!
But, how i can disable the tests generation?

**Comment by jaggli** [comment]
Currently there is no way to disable it, but this is a good idea. Currently I'm in vacation, but I will take care about it, as soon as I'm back - or of course you're very welcome to submit a pull request for adding this option.

**Comment by jaggli** [comment]
fixed in v2.3.0
