### ISSUE TITLE
Error: `Unable to find node on an unmounted component` when using imported component

### ISSUE THREAD

**Issue by mokkymiah** [Scout24-CH/styled-svg#11]
Hello I am importing an icon and when I use it, I get the following error;

`Unable to find node on an unmounted component.`

Example

```js
import HomeIcon from '../icons/Logo';

return (
    <Logo />
)
```

You can recreate the issue in this repo I created;
https://github.com/mokkymiah/styled-svg-test

It's a standard `create-react-app` and I am importing the default logo.

**Comment by jaggli** [comment]
Thanks for reporting, will look into it

**Comment by jaggli** [comment]
This is not reproducible anymore with the most recent version of styled-svg.  
Please have a look over here https://github.com/jaggli/styled-svg-test
